### ISSUE TITLE
Clarify what deleting keys from staking pool means

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/stakewars#343] opened 2020-05-27 11:01 UTC
People just delete key folder instead of deleting full access key on the contract.

**Comment by jimmy3dita** [comment] 2020-05-27 18:18
Added in the new challenges section. Will be covered by some tutorial too

**Comment by evgenykuzyakov** [comment] 2020-05-27 19:57
I've merged staking pool factory contract. Going to build the UI that lets people deploy a new staking pool.
The issue is deleting keys from the account will break the logic within contract, because you shouldn't issue any transaction from the staking pool, once it's initialized

**Comment by jimmy3dita** [comment] 2020-05-28 02:38
I got a pair of contracts that got locked using `near delete-key`. What could happen?

**Comment by bowenwang1996** [comment] 2020-05-28 02:51
> What could happen?

If you mean staking contracts then it is supposed to work like that.

**Comment by jimmy3dita** [comment] 2020-05-29 01:34
To be clear: there's no issue in deploying the staking pool, and delete the keys right after by using `near delete-key`? 
I understood that it's sub-optimal to use this process, and the staking pool keys should be deleted at the deployment (which is possible only via libraries).

**Comment by bowenwang1996** [comment] 2020-05-29 15:16
> there's no issue in deploying the staking pool, and delete the keys right after by using near delete-key

I think that's fine. Just make sure that you do it before initializing the contract.

**Comment by jimmy3dita** [comment] 2020-06-02 19:55
@bowenwang1996 I think I need more details in your answer. How can I initialize the contract with `near call <staking_pool_id> new` after deleting the keys?

**Comment by bowenwang1996** [comment] 2020-06-02 20:04
Just realized that what I said doesn't make sense. There is no good way to do this so it is better to use factory instead.

**Comment by jimmy3dita** [comment] 2020-06-02 20:56
I suppose that some users used the `delete-key` command:
- how do they detect any inconsistent state?
- what is the ideal remediation?

**Comment by bowenwang1996** [comment] 2020-06-03 00:02
> how do they detect any inconsistent state?

They can detect it by invoking any of the function that changes its state, such as stake, unstake, deposit, withdraw.

> what is the ideal remediation?

There is no "ideal" remediation, but one hack to get around this is to transfer a small number of tokens to the contract account (usually 1 NEAR will be sufficient).

**Closed** 2020-07-10 17:44 UTC
