### ISSUE TITLE
Different result in runing docker and runing without docker 

### ISSUE THREAD

**Issue by hoekevin** [nearprotocol/stakewars#5] opened 2019-10-24 04:12 UTC
### **The error below occured where docker is runing:**

================================================================
[2019-10-24T03:00:59Z INFO  near_client::info] #   23356 Downloading blocks 99% -/2  3/3/40 peers ⬇ 215.6kiB/s ⬆ 2.3kiB/s 0.00 bps 0 gas/s CPU: 8%, Mem: 164.3 MiB
[2019-10-24T03:01:09Z INFO  near_client::info] #   23356 Downloading blocks 99% -/2  3/2/40 peers ⬇ 213.9kiB/s ⬆ 2.3kiB/s 0.00 bps 0 gas/s CPU: 6%, Mem: 164.3 MiB
[2019-10-24T03:01:19Z INFO  near_client::info] #   23356 Downloading blocks 99% -/2  3/3/40 peers ⬇ 222.1kiB/s ⬆ 2.4kiB/s 0.00 bps 0 gas/s CPU: 7%, Mem: 164.3 MiB
[2019-10-24T03:01:29Z INFO  near_client::info] #   23356 Downloading blocks 99% -/2  3/2/40 peers ⬇ 222.8kiB/s ⬆ 2.4kiB/s 0.00 bps 0 gas/s CPU: 6%, Mem: 164.3 MiB
[2019-10-24T03:01:39Z INFO  near_client::info] #   23356 Downloading blocks 99% -/2  3/1/40 peers ⬇ 224.5kiB/s ⬆ 2.5kiB/s 0.00 bps 0 gas/s CPU: 7%, Mem: 164.3 MiB
[2019-10-24T03:01:47Z ERROR near_client::sync] State sync: block request for CKMXpbCHMZuppFzHmVJobZJokX7Q4KuxS6rb3tPicfoM timed out in 10 seconds
[2019-10-24T03:01:49Z INFO  near_client::info] State 5: header1: header0: header2: header3: header6: header7: header4: header -/2  3/2/40 peers ⬇ 232.1kiB/s ⬆ 2.5kiB/s 0.00 bps 0 gas/s CPU: 6%, Mem: 164.3 MiB
[2019-10-24T03:01:57Z ERROR near_client::sync] State sync: state download for shard 0 timed out in 10 seconds
[2019-10-24T03:01:57Z ERROR near_client::sync] State sync: state download for shard 1 timed out in 10 seconds
[2019-10-24T03:01:57Z ERROR near_client::sync] State sync: state download for shard 2 timed out in 10 seconds
[2019-10-24T03:01:57Z ERROR near_client::sync] State sync: state download for shard 3 timed out in 10 seconds
[2019-10-24T03:01:57Z ERROR near_client::sync] State sync: state download for shard 4 timed out in 10 seconds
[2019-10-24T03:01:57Z ERROR near_client::sync] State sync: state download for shard 5 timed out in 10 seconds
[2019-10-24T03:01:57Z ERROR near_client::sync] State sync: state download for shard 6 timed out in 10 seconds
[2019-10-24T03:01:57Z ERROR near_client::sync] State sync: state download for shard 7 timed out in 10 seconds
..................................
ignor same message here
..................................
[2019-10-24T03:04:29Z INFO  near_client::info] State 5: done1: parts0: done2: done3: parts6: parts7: parts4: done -/2  4/4/40 peers ⬇ 180.6kiB/s ⬆ 0.7kiB/s 0.00 bps 0 gas/s CPU: 8%, Mem: 184.0 MiB
[2019-10-24T03:04:37Z ERROR near_client::sync] State sync: state download for shard 3 timed out in 10 seconds
[2019-10-24T03:04:37Z ERROR near_client::sync] State sync: state download for shard 1 timed out in 10 seconds
[2019-10-24T03:04:39Z INFO  near_client::info] State 5: done1: parts0: done2: done3: parts6: done7: done4: done -/2  4/3/40 peers ⬇ 238.0kiB/s ⬆ 0.7kiB/s 0.00 bps 0 gas/s CPU: 9%, Mem: 185.5 MiB
[2019-10-24T03:04:49Z ERROR near_client::sync] State sync: block request for DDFNLax7bgEGmQ7cbZcs3z5KiCYJRwJnjcbkgje7grAB timed out in 10 seconds
[2019-10-24T03:04:49Z INFO  near_client::info] State 3: header4: header7: header5: header1: header0: header6: header2: header -/2  4/4/40 peers ⬇ 267.6kiB/s ⬆ 0.4kiB/s 0.00 bps 0 gas/s CPU: 4%, Mem: 185.5 MiB
/usr/local/bin/run.sh: line 24:    30 Illegal instruction     (core dumped) near --home=${NEAR_HOME} run --boot-nodes=${BOOT_NODES}
*** /usr/local/bin/run.sh exited with status 132.
*** Shutting down runit daemon (PID 25)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Oct 24 03:04:57 f7c63ad81b12 syslog-ng[16]: syslog-ng shutting down; version='3.13.2'
*** Killing all processes...

================================================================
### **Then I stopped the container and runed nearcore with --nodocker using the same .near folder, It could  work well and the "V" sign appeared properly.
I don't know what reason cause these,but I think may it is a bug of docker images.**  

================================================================
[2019-10-24T04:06:02Z INFO  near_client::info] #   24531 HVqL3ZAmAE7TRzPRgM6Kj5KusiBVtwpn8rd4eyDtmb5a V/1  6/1/40 peers ⬇ 24.1kiB/s ⬆ 83.4kiB/s 1.00 bps 0 gas/s CPU: 6%, Mem: 159.0 MiB
[2019-10-24T04:06:12Z INFO  near_client::info] #   24541 9kz4HfH2xZ2h8q8yo1YXTMG6ZqL3pPbZPqhCdMoBhz56 V/1  6/1/40 peers ⬇ 23.8kiB/s ⬆ 82.8kiB/s 1.00 bps 0 gas/s CPU: 7%, Mem: 160.3 MiB
[2019-10-24T04:06:22Z INFO  near_client::info] #   24550 68cGhL2qZMmGQRDFbuGc5b2nghZxo23b32V5Vrrn7kqb V/1  6/1/40 peers ⬇ 24.4kiB/s ⬆ 84.1kiB/s 0.90 bps 0 gas/s CPU: 6%, Mem: 160.3 MiB
[2019-10-24T04:06:32Z INFO  near_client::info] #   24560 64JpHZ1SqQS846BqPZ4Z8LNoEyfbgNSNDj1ty43M3GUm V/1  6/1/40 peers ⬇ 24.7kiB/s ⬆ 84.9kiB/s 1.00 bps 0 gas/s CPU: 7%, Mem: 160.4 MiB

**Comment by hoekevin** [comment] 2019-10-26 11:23
# #2

**Comment by bowenwang1996** [comment] 2019-11-14 18:41
Looks like it's caused by instability of state sync rather than docker.

**Comment by bowenwang1996** [comment] 2019-11-14 19:05
The problem should be fixed in the new version.

**Closed by bowenwang1996** 2019-11-14 19:05 UTC
Labels: S2, duplicate
