### ISSUE TITLE
[BUG] Wallet on create account screen misleading Account already taken message

### ISSUE THREAD

**Issue by krisboit** [nearprotocol/stakewars#93] opened 2019-12-18 00:05 UTC
**Describe the bug or test**
On create account screen if the call to `https://tatooine-account-helper.onrender.com/account` fails wallet displays a misleading error: `Username is taken. Try something else.`. 

**How to Reproduce**
1. Go to https://wallet.tatooine.nearprotocol.com/create
2. Enter a valid username

**Expected behavior OR Outcome of test**
This error should be treated separately, and display a relevant error message.

**Screenshots Optional**
<img width="1271" alt="Screenshot 2019-12-18 at 02 00 37" src="https://user-images.githubusercontent.com/9469296/71044632-df83d480-213a-11ea-8a3a-d80d53464b55.png">

**Comment by frol** [comment] 2019-12-18 08:05
Closing as duplicate of #65.

**Closed by frol** 2019-12-18 08:05 UTC
Labels: totriage
